services:
  tienda-db:
    build: ./db
    container_name: tienda-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tienda_perritos
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  tienda-backend:
    build: ./backend
    container_name: tienda-backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST: tienda-db
      DB_USER: root
      DB_PASSWORD: admin123
      DB_NAME: tienda_perritos
      DB_PORT: 3306
    depends_on:
      tienda-db:
        condition: service_healthy

  tienda-frontend:
    build: ./frontend
    container_name: tienda-frontend
    ports:
      - "80:80"
    depends_on:
      - tienda-backend

volumes:
  mysql_data:
